/*
 * seo.js — turn a page document plus the site settings into the exact tag
 * sequence that goes into <head>.
 *
 * Rules (from reco.md sections 5 and 9):
 *   - canonical is always the current locale's URL, never cross-locale
 *   - x-default always points at the English version
 *   - a locale with no translation gets no hreflang entry at all
 *   - a page reached with ?version= emits noindex, nofollow
 *   - empty fields emit no tag: never content=""
 *   - OG falls back to the global defaults from the CMS settings
 *   - JSON-LD is server rendered, auto-generated per page type, and can be
 *     extended or replaced from the CMS
 */
import { escapeAttr } from './html.js';

const trimSlash = (s) => String(s || '').replace(/\/+$/, '');

export function absoluteUrl(baseUrl, path) {
  if (!path) return trimSlash(baseUrl) + '/';
  if (/^https?:\/\//i.test(path)) return path;
  return trimSlash(baseUrl) + (path.startsWith('/') ? path : '/' + path);
}

/**
 * Public URL of a page in a given locale.
 *
 * No trailing slash, except on a locale root (`/fr/`), and that is not a
 * cosmetic preference. The authored pages link to each other as
 * `href="/fr/tarifs"`, and those bytes are under the fidelity guarantee —
 * `verify-live` asserts the site still ships them exactly. So the site's own
 * links cannot be given a trailing slash, and a canonical tag that had one
 * meant every internal link on the site pointed at a non-canonical URL while
 * both forms answered 200. That is duplicate content generated by the CMS
 * itself, and the half that has to move is the generated half.
 */
export function pageUrl(baseUrl, locale, route) {
  const clean = String(route || '').replace(/^\/+|\/+$/g, '');
  const path = clean ? `/${locale}/${clean}` : `/${locale}/`;
  return trimSlash(baseUrl) + path;
}

/**
 * The route a page answers to in one locale.
 *
 * A page carries a base route (the source language's path) and an optional
 * per-locale override, so German visitors get `/de/preise` rather than
 * `/de/tarifs`. An absent or empty override falls back to the base route: a
 * locale nobody has translated the path for keeps working rather than 404ing.
 * Accepts a Map (Mongoose) or a plain object (JSON payload) indifferently.
 */
export function routeFor(page, locale) {
  const routes = page?.routes;
  const raw = routes instanceof Map ? routes.get(locale) : routes?.[locale];
  const value = raw === undefined || raw === null || raw === '' ? page?.route : raw;
  return String(value || '').replace(/^\/+|\/+$/g, '');
}

/** Public URL of a page in a locale, honouring its localized route. */
export function pageUrlFor(baseUrl, locale, page) {
  return pageUrl(baseUrl, locale, routeFor(page, locale));
}

/** The blog's own path segment in a locale (`blog` unless overridden). */
export function blogSegmentFor(settings, locale) {
  const map = settings?.blogSegment;
  const raw = map instanceof Map ? map.get(locale) : map?.[locale];
  const value = String(raw || '').replace(/^\/+|\/+$/g, '');
  return value || 'blog';
}

/** `donnees-hebergees-en-france` → `Donnees hebergees en france`. */
function humanise(segment) {
  const words = String(segment || '').replace(/[-_]+/g, ' ').trim();
  return words ? words[0].toUpperCase() + words.slice(1) : '';
}

function tag(name, attrs) {
  const parts = Object.entries(attrs)
    .filter(([, v]) => v !== undefined && v !== null && String(v).length > 0)
    .map(([k, v]) => `${k}="${escapeAttr(v)}"`);
  if (!parts.length) return '';
  return `<${name} ${parts.join(' ')}>`;
}

/**
 * Build the <head> metadata block.
 *
 * page      { route, seo: {...per locale resolved}, type }
 * ctx       { baseUrl, locale, locales:[{code, active}], translations:{locale:route},
 *             settings, noindex }
 */
export function buildHead(page, ctx) {
  const s = page.seo || {};
  const g = ctx.settings || {};
  const out = [];
  const url = pageUrl(ctx.baseUrl, ctx.locale, page.route);

  const title = s.title || g.defaultTitle || '';
  const description = s.description || g.defaultDescription || '';

  if (title) out.push(`<title>${escapeAttr(title)}</title>`);
  if (description) out.push(tag('meta', { name: 'description', content: description }));
  if (s.keywords) out.push(tag('meta', { name: 'keywords', content: s.keywords }));

  const robots = ctx.noindex ? 'noindex, nofollow' : (s.robots || 'index, follow');
  out.push(tag('meta', { name: 'robots', content: robots }));

  if (!ctx.noindex) {
    out.push(tag('link', { rel: 'canonical', href: s.canonical || url }));
    for (const alt of ctx.translations || []) {
      out.push(tag('link', { rel: 'alternate', hreflang: alt.locale, href: alt.url }));
    }
    const en = (ctx.translations || []).find(t => t.locale === 'en');
    if (en) out.push(tag('link', { rel: 'alternate', hreflang: 'x-default', href: en.url }));
  }

  // Open Graph — per-page values win, global defaults fill the gaps, empty
  // fields emit nothing at all.
  const ogTitle = s.ogTitle || g.defaultOgTitle || title;
  const ogDescription = s.ogDescription || g.defaultOgDescription || description;
  const ogImage = s.ogImage || g.defaultOgImage;
  out.push(tag('meta', { property: 'og:type', content: s.ogType || 'website' }));
  if (ogTitle) out.push(tag('meta', { property: 'og:title', content: ogTitle }));
  if (ogDescription) out.push(tag('meta', { property: 'og:description', content: ogDescription }));
  out.push(tag('meta', { property: 'og:url', content: url }));
  if (g.siteName) out.push(tag('meta', { property: 'og:site_name', content: g.siteName }));
  out.push(tag('meta', { property: 'og:locale', content: ctx.locale }));
  if (ogImage) out.push(tag('meta', { property: 'og:image', content: absoluteUrl(ctx.baseUrl, ogImage) }));

  const twitterCard = s.twitterCard || (ogImage ? 'summary_large_image' : 'summary');
  out.push(tag('meta', { name: 'twitter:card', content: twitterCard }));
  if (s.twitterTitle || ogTitle) out.push(tag('meta', { name: 'twitter:title', content: s.twitterTitle || ogTitle }));
  if (s.twitterDescription || ogDescription) out.push(tag('meta', { name: 'twitter:description', content: s.twitterDescription || ogDescription }));
  if (s.twitterImage || ogImage) out.push(tag('meta', { name: 'twitter:image', content: absoluteUrl(ctx.baseUrl, s.twitterImage || ogImage) }));

  return out.filter(Boolean).map(t => '    ' + t).join('\n');
}

/** Wrap a JSON-LD payload in a script tag. Arrays are emitted one tag each. */
export function jsonLdTag(payload) {
  if (!payload) return '';
  const body = typeof payload === 'string' ? payload : JSON.stringify(payload, null, 2);
  if (!body.trim()) return '';
  return `    <script type="application/ld+json">\n${body}\n    </script>`;
}

/**
 * Auto-generated structured data per page type (reco.md 5.2), plus whatever the
 * editor added. `replaceAutoLd` swaps the auto block out entirely.
 */
export function buildJsonLd(page, ctx) {
  const s = page.seo || {};
  const g = ctx.settings || {};
  const url = pageUrl(ctx.baseUrl, ctx.locale, page.route);
  const org = {
    '@type': 'Organization',
    name: g.organizationName || g.siteName || 'Rainbow by ALE',
    url: trimSlash(ctx.baseUrl) + '/',
    ...(g.organizationLogo ? { logo: absoluteUrl(ctx.baseUrl, g.organizationLogo) } : {}),
    ...(Array.isArray(g.socialProfiles) && g.socialProfiles.length ? { sameAs: g.socialProfiles } : {}),
  };

  const blocks = [];
  const kind = page.schemaType || page.pageKind || 'page';
  const blogSegment = blogSegmentFor(g, ctx.locale);

  if (kind === 'home') {
    blocks.push({ '@context': 'https://schema.org', ...org });
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: g.siteName || org.name,
      url: trimSlash(ctx.baseUrl) + `/${ctx.locale}/`,
      inLanguage: ctx.locale,
      potentialAction: {
        '@type': 'SearchAction',
        target: `${trimSlash(ctx.baseUrl)}/${ctx.locale}/${blogSegment}/?q={search_term_string}`,
        'query-input': 'required name=search_term_string',
      },
    });
  } else if (kind === 'product') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: s.title || page.title,
      description: s.description,
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web, Windows, macOS, iOS, Android',
      url,
      ...(g.organizationName ? { publisher: { '@type': 'Organization', name: g.organizationName } } : {}),
    });
  } else if (kind === 'blogIndex') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'Blog',
      name: s.title || page.title,
      description: s.description,
      url,
      inLanguage: ctx.locale,
      publisher: org,
    });
  } else if (kind === 'blogPost') {
    const post = ctx.post || {};
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: s.title || post.title,
      description: s.description || post.excerpt,
      ...(post.coverImage ? { image: [absoluteUrl(ctx.baseUrl, post.coverImage)] } : {}),
      datePublished: post.publishedAt,
      dateModified: post.updatedAt || post.publishedAt,
      author: { '@type': 'Person', name: post.authorName || org.name },
      publisher: org,
      mainEntityOfPage: { '@type': 'WebPage', '@id': url },
      inLanguage: ctx.locale,
    });
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${trimSlash(ctx.baseUrl)}/${ctx.locale}/` },
        { '@type': 'ListItem', position: 2, name: 'Blog', item: `${trimSlash(ctx.baseUrl)}/${ctx.locale}/${blogSegment}/` },
        { '@type': 'ListItem', position: 3, name: s.title || post.title, item: url },
      ],
    });
  } else if (kind !== 'error' && page.route) {
    // Every other page gets a breadcrumb too: it is what puts the path rather
    // than the bare domain under a search result, and it costs one object.
    //
    // Intermediate levels are only listed when the frontend has told us that
    // route exists (`ctx.knownRoutes`). Linking a crawler at `/fr/products/`
    // because a page happens to live at `/fr/products/collaboration` would
    // point it at a 404, which is worse than a shorter trail.
    const trail = String(page.route).split('/').filter(Boolean);
    const items = [{ '@type': 'ListItem', position: 1, name: 'Home', item: `${trimSlash(ctx.baseUrl)}/${ctx.locale}/` }];
    let walked = '';
    for (let i = 0; i < trail.length; i++) {
      walked += (walked ? '/' : '') + trail[i];
      const last = i === trail.length - 1;
      if (!last && !ctx.knownRoutes?.has(walked)) continue;
      items.push({
        '@type': 'ListItem',
        position: items.length + 1,
        name: last ? (s.title || page.title) : humanise(trail[i]),
        item: pageUrl(ctx.baseUrl, ctx.locale, walked),
      });
    }
    if (items.length > 1) {
      blocks.push({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: items });
    }
  }

  const tags = [];
  if (!s.replaceAutoLd) {
    for (const b of blocks) tags.push(jsonLdTag(b));
    // Structured data authored inside the original template (kept translatable).
    for (const raw of page.jsonLd || []) tags.push(jsonLdTag(raw));
  }
  if (s.jsonLdOverride) tags.push(jsonLdTag(s.jsonLdOverride));
  return tags.filter(Boolean).join('\n');
}
